spring:
  datasource:
    url: jdbc:h2:file:./data/mydb;INIT=RUNSCRIPT FROM './data/create.sql';auto_server=true;mode=mysql  # 数据库
    driver-class-name: org.h2.Driver
    username: root
    password: 123456
  h2:
    console:
      path: /h2-console  #h2嵌入式数据库控制台，可以通过浏览器访问
      enabled: true
